<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ocl" nsURI="http://www.example.org/ocl" nsPrefix="ocl">
  <eClassifiers xsi:type="ecore:EClass" name="EOclExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopBodyOwner" eType="#//ELoopExp"
        eOpposite="#//ELoopExp/body"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedElement" eType="#//ECallExp"
        eOpposite="#//ECallExp/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializedElement" eType="#//EVariable"
        eOpposite="#//EVariable/initExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenOwner" eType="#//EIfExp"
        eOpposite="#//EIfExp/thenExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifOwner" eType="#//EIfExp"
        eOpposite="#//EIfExp/condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseOwner" eType="#//EIfExp"
        eOpposite="#//EIfExp/elseExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentCall" eType="#//EOperationCallExp"
        eOpposite="#//EOperationCallExp/argument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNav" eType="#//ENavigationCallExp"
        eOpposite="#//ENavigationCallExp/qualifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECallExp" abstract="true" eSuperTypes="#//EOclExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//EOclExpression"
        containment="true" eOpposite="#//EOclExpression/appliedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELiteralExp" abstract="true" eSuperTypes="#//EOclExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EIfExp" eSuperTypes="#//EOclExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1"
        eType="#//EOclExpression" containment="true" eOpposite="#//EOclExpression/thenOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//EOclExpression" containment="true" eOpposite="#//EOclExpression/ifOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" lowerBound="1"
        eType="#//EOclExpression" containment="true" eOpposite="#//EOclExpression/elseOwner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVariableExp" eSuperTypes="#//EOclExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" eType="#//EVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeExp" eSuperTypes="#//EOclExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMessageExp" eSuperTypes="#//EOclExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EStateExp" eSuperTypes="#//EOclExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFeatureCallExp" abstract="true" eSuperTypes="#//ECallExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELoopExp" abstract="true" eSuperTypes="#//ECallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//EOclExpression"
        containment="true" eOpposite="#//EOclExpression/loopBodyOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" upperBound="-1"
        eType="#//EVariable" containment="true" eOpposite="#//EVariable/loopExp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EIteratorExp" eSuperTypes="#//ELoopExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EIterateExp" eSuperTypes="#//ELoopExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//EVariable"
        containment="true" eOpposite="#//EVariable/baseExp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopExp" eType="#//ELoopExp"
        eOpposite="#//ELoopExp/iterator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseExp" eType="#//EIterateExp"
        eOpposite="#//EIterateExp/result"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//EOclExpression"
        containment="true" eOpposite="#//EOclExpression/initializedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPrimitiveType" abstract="true" eSuperTypes="#//ELiteralExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENumericLiteralExp" abstract="true"
      eSuperTypes="#//EPrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EIntegerLiteralExp" eSuperTypes="#//ENumericLiteralExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringLiteralExp" eSuperTypes="#//EPrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBooleanLiteralExp" eSuperTypes="#//EPrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENavigationCallExp" abstract="true"
      eSuperTypes="#//EFeatureCallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" upperBound="-1"
        eType="#//EOclExpression" containment="true" eOpposite="#//EOclExpression/parentNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOperationCallExp" eSuperTypes="#//EFeatureCallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
        eType="#//EOclExpression" containment="true" eOpposite="#//EOclExpression/parentCall"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPropertyCallExp" eSuperTypes="#//ENavigationCallExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredProperty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAssociationClassCallExp" eSuperTypes="#//ENavigationCallExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referredAssociationEnds"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
